### ISSUE TITLE
[Chore] - Add empty table body

### ISSUE THREAD

**Issue by jdwilkin4** [jdwilkin4/fcc-forum-clone#11]
### What work needs to be done?

**Please note:**
It would be best to work on this issue, when #9 has been merged.

Since we will be working with a table, we will need to add an empty `tbody` to start. 
This is where all of the forum posts will go.

Inside the `table` and just after the `thead`, place a `tbody` element.
For that `tbody` element, add an id. 
Give that id a name like `posts-container` or `forum-posts`.

Then at the top of the `index.js` file, target that id using `getElementById` and assign it to a new variable. 

For example, something like this:
```
const postsContainer = document.getElementById("posts-container");

```

**Comment by Dorfieeee** [comment]
@dgupta0
You can start working on this issue if you like :]

**Comment by dgupta0** [comment]
I will look into and work on it soon :)
