### ISSUE TITLE
[Feature] - Add total views for each forum post

### ISSUE THREAD

**Issue by jdwilkin4** [jdwilkin4/fcc-forum-clone#23]
### What feature would you like to see?

**Please note: Work on this should not start until the  Basic Project Setup milestone is complete.**

Each forum post will have the total number of views displayed
<img width="335" alt="Screen Shot 2022-09-23 at 12 12 22 AM" src="https://user-images.githubusercontent.com/67210629/191908933-30d32644-339c-43fd-99a3-4a3e4edbd711.png">

If the views are 1000 or more, then you will want to drop the zeros and add a k at the end. 

Here are some examples:
1000 views = 1k
12,000 = 12k
113,000 = 113k

You are trying to mimic the same behavior that is found on the actual forum
<img width="260" alt="Screen Shot 2022-09-23 at 12 23 32 AM" src="https://user-images.githubusercontent.com/67210629/191910434-874f3f1c-3c21-4375-826e-b9245f32ea96.png">

**Comment by Dorfieeee** [comment]
Task: write a function `formatLargeNumber` which accepts a parameter `n`(integer) and returns
a string `s`, which takes the following format:
n < 1000; s = "n"
n >= 1000; s = "(n / 1000)k" where n rounded to 1 decimal place

**Comment by Dorfieeee** [comment]
@thetalesofj if you feel unstoppable now, you can try do this one as well.
Follow the tasks instruction above and store the function in `helpers.js`, export it and import to `index.js`.
Then you only need to apply the same logic as in the previous issue with the difference that you'll pass
the views property as parameter to `formatLargeNumber`.
