### ISSUE TITLE
[Docs] - Add contributing file to project

### ISSUE THREAD

**Issue by jdwilkin4** [jdwilkin4/fcc-forum-clone#4]
### What changes would you like to make in the documentation?

Since this is an open source project, we should add a `CONTRIBUTING.md` file to the root directory. 

Here are some examples of contributing files to help you create one.
https://github.com/github/docs/blob/main/CONTRIBUTING.md
https://github.com/DBenMoshe/contrast-ratio-repo/blob/main/CONTRIBUTING.md

**Comment by AndreyDmitriev39r** [comment]
We actually have instruction about contributing in the README right now. Do we need to remove this information from README, when working on this ticket?

**Comment by jdwilkin4** [comment]
It is fine to link to the contributing docs
