### ISSUE TITLE
[Bug] - Multiple elements with the same ID

### ISSUE THREAD

**Issue by Dorfieeee** [jdwilkin4/fcc-forum-clone#43]
Hello @sparkO7 

I've also noticed that you use IDs for styling, this is not inherently bad idea, however, we generate several
posts and each one them contains the same ID name, resulting in multiple IDs in the same HTML document.
`id` attribute is a global identifier and [must be unique](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id) in the whole document.

Could you please fix it?

https://github.com/jdwilkin4/fcc-forum-clone/blob/9ec2d6d31a8be90754ed74cb00836a129cc88b4b/index.js#L46-L66

**Comment by sparkO7** [comment]
Oh that is right.
