### ISSUE TITLE
[Feature] - Add buttons to support filtering by category

### ISSUE THREAD

**Issue by ChefDaddyJay** [jdwilkin4/fcc-forum-clone#57]
### Description
Add HTML and CSS to display buttons above the posts table to support future ability to filter the posts by category.
During this issue, you will learn how to use [Map object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) and do basic operations on it. You will practice dynamical access to object properties and working with DOM.

1. Place this between the title and the table.
```
<div id="filter-btns">
 // space for future buttons
</div>
```

2. Declare a Map object called `categories` on top of the index.js among other declarations. This will hold key value pairs representing category_id and its count.
3. Declare a function called `displayCategories`
4. Inside that `displayCategories` function
    1. loop through all items in `forumData.topic_list.topics` and check whether the `categories` Map object contains the topic's `category_id`. If it does, increase its value by 1, otherwise add the `category_id` to the map and set its value to 1.  
    2. loop through `categories`(you declared in step 3) and for each item(=category_id, count) add the following inside the `filter-btns` div you created in step 1. Please note that you will need to replace the `{category_id}` and `{count}` with the variables holding its value. The following code serves as a template for you to work with.
    ```
        <button
             name="filter-button" 
             value={category_id}
             class=supportedTopicCategories[{category_id}].name
             >
                 supportedTopicCategories[category_id].longName ({count})
        </button>
    ``` 
eg. the final button HTML for JavaScript category should look like this:
```
        <button
             name="filter-button" 
             value="421"
             class="javascript"
             >
                 JavaScript (5) // The count is made up, it can be any number
        </button>
```
Don't worry about styling right now. This tasks is large enough already.

### Design
Interactive [Figma design](https://www.figma.com/proto/UYXlxWMdsz5Z69WD1s4HK8/fcc-forum-table-(Copy)?node-id=202%3A3&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=202%3A3)

![image](https://user-images.githubusercontent.com/65303812/203545093-9cabd12f-35ab-454d-96a4-aaa6cc7a7c15.png)

**Comment by Dorfieeee** [comment]
Shouldn't the name be the same for all buttons?

**Comment by ChefDaddyJay** [comment]
You're right, I edited the description to show that
