### ISSUE TITLE
[Style] - Add the nav bar styles

### ISSUE THREAD

**Issue by jdwilkin4** [jdwilkin4/fcc-forum-clone#6]
### What is your UI design change or proposal?

Here is the figma design for the navbar

https://www.figma.com/file/zcLQ1my10Lp2yAVAIZcOWh/fcc-forum-nav?node-id=0%3A1

Make sure to use the exact hex code specified in the figma mockup needed for the background color.
For the freeCodeCamp logo, you can get it from the figma mockup or from the [official fcc style guide](https://design-style-guide.freecodecamp.org/).  
In the style guide, it is listed as primary logo. 

When the user clicks on the logo, it should open up a new browser tab to the actual fcc forum page.

**Comment by AndreyDmitriev39r** [comment]
I am not sure about hte issue scope from the issue name: do I need just add styles to CSS, or do I also need to add actual HTML?

**Comment by jdwilkin4** [comment]
You will need to add both html and css to add the navbar.
