### ISSUE TITLE
[Feature] - Include FontAwesome library

### ISSUE THREAD

**Issue by Dorfieeee** [jdwilkin4/fcc-forum-clone#62]
## Description

This task requires you to add a single line of code to the index.html, but it may take you some time to figure out what you need to do to achieve the objective.

As you can see in this [Figma design](https://www.figma.com/proto/UYXlxWMdsz5Z69WD1s4HK8/fcc-forum-table-(Copy)?node-id=202%3A3&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=202%3A3), when users clicks on any sort button, an arrow icon appears and when clicked again, the arrow changes its direction. For that, we could create some .png image, but it is better to use icons instead. There are many icon libraries and [FontAwesome](https://fontawesome.com/) is one of them, offering many icons for free.

### Objective
Update the index.html file so it includes version 6.x of the FontAwesome library.
Try to use CDN link rather than creating your account.

**Comment by dgupta0** [comment]
The figma file isn't loading.
