### ISSUE TITLE
[Style] - Fix layout shift

### ISSUE THREAD

**Issue by Dorfieeee** [jdwilkin4/fcc-forum-clone#63]
### What is your UI design change or proposal?

Have you noticed that before the forum posts are loaded and rendered, the `<footer>` is in the middle of the screen as the table is empty?
![Screenshot 2022-11-23 100010](https://user-images.githubusercontent.com/65303812/203521732-4fe42c56-f216-46ad-ab26-024d81cd4102.jpg)
We need to change this so the table takes as much space as it would with the posts there already. You can assume that space for 30 posts will be needed initially. It does not need to be the exact size as some posts can contain more content than others.
(Solution to this may bring up another issue which will be opened once you figure out what it is)

**Comment by dgupta0** [comment]
Hey!! Do we have this issue because the footer isn't positioned at the bottom?
