### ISSUE TITLE
[Feature] - Add mechanism to sort the topics

### ISSUE THREAD

**Issue by Dorfieeee** [jdwilkin4/fcc-forum-clone#70]
### What feature would you like to see?

**Please note this should only be worked on after https://github.com/jdwilkin4/fcc-forum-clone/issues/69 is completed**

By now, we should have all the tools we need to sort the topics.
We know by what it needs to be sorted, `sortingBy` and in what order, `sortingOrder`.

### Task
You should be able to modify the `handleSortBtnClick` to add the sorting logic for the currently displayed topics by those two criteria. There are many ways to do it. You may need to manipulate the DOM or use the data stored in `forumData`. You may also come up with another and better way.

### Good to know
You are highly encouraged to use existing functions such as `displayPostList`. You are also encouraged to modify those functions as you need, just make sure everything else works as it should, or even better.

**Comment by AndreyDmitriev39r** [comment]
I am grabbing this issue, cause I've started to work on #68 and just can't think of way not to work on #69 at the same time lol
