### ISSUE TITLE
[Chore] - The First PR

### ISSUE THREAD

**Issue by Dorfieeee** [jdwilkin4/fcc-forum-clone#73]
### What work needs to be done?

Use this issue to create your first pull request(PR).

You can find and correct any typos or grammatical errors in our documentation files or inside the comments in the code.
It can be just a comma or anything. This issue mainly serves as a practice of working with git commands.

[README](https://github.com/jdwilkin4/fcc-forum-clone/blob/v1/README.md)
[CONTRIBUTING_GUIDE](https://github.com/jdwilkin4/fcc-forum-clone/blob/v1/CONTRIBUTING.md)

**Comment by ShawnKellyWright** [comment]
Excellent, thank you so much.
I will try my best when working on this.

Thanks,
Shawn Wright

**Comment by Dorfieeee** [comment]
@ShawnKellyWright don't forget about this! 💯 😛
