### ISSUE TITLE
[Style] - CSS changes | div id of #filter-btns is misaligned

### ISSUE THREAD

**Issue by dgupta0** [jdwilkin4/fcc-forum-clone#81]
### What is your UI design change or proposal?

The container with id of `#filter-btns`  can be better aligned. 
Currently if we open the clone site- https://fcc-forum-clone.netlify.app/, 
the container is pushed to its left side-
Image below-
<img width="499" alt="Screenshot 2023-02-25 at 11 23 10 AM" src="https://user-images.githubusercontent.com/108337465/221341340-e9c34fd4-b595-486c-a9f4-8815a2cbc203.png">

We can center the container and make the UI look better.

**Comment by Dorfieeee** [comment]
It would be nice to make them look prettier too.

**Comment by dgupta0** [comment]
Thanks! How can I do that? The visual reference is for which element we have to modify.

**Comment by dgupta0** [comment]
Let me know if I should make it prettier? Thanks!!

**Comment by Dorfieeee** [comment]
Style the filter buttons. I'll leave that up to your imagination.

**Comment by dgupta0** [comment]
I can create a separate task for styling the css button. Right now there's
no space between the left side and  the #filter-btn container.  I need more
hints maybe. Thanks!

**Comment by RahulRana701** [comment]
hey @Dorfieeee can you assign it to me , I think I can solve this issue , so I would like to work on it....

**Comment by Dorfieeee** [comment]
@RahulRana701 hey!

As a bonus: feel free to add your own style to those buttons if you like.

**Comment by RahulRana701** [comment]
Hey @Dorfieeee I have made the pull request you can check it out. #88 ..https://github.com/jdwilkin4/fcc-forum-clone/pull/88#issue-1609950773

**Comment by RahulRana701** [comment]
hey @Dorfieeee I am not able to find the html inside the id filter-btns which is written for the buttons, due to that I am not able to access those buttons..

**Comment by RahulRana701** [comment]
hey @Dorfieeee I have made a new pull request please review and merge it , I think this pull request will solve the issue..https://github.com/jdwilkin4/fcc-forum-clone/pull/89#issue-1610094597

**Comment by RahulRana701** [comment]
hey @Dorfieeee how do I know if my pr is merged..can you please tell...

**Comment by Dorfieeee** [comment]
@RahulRana701 you'll get a notification and will see that in the PR details.
@AndreyDmitriev39r had some change request and he might not have the time to review it over the weekend.
